
train_set_path : data/train_sources
train_set_dynamic_mixing : True
valid_set_path : data/validation
val_check_interval : 5000
max_duration: 96000
use_high_pass : True
batch_size: 4
num_worker : 2

# BS=2, ~ 14G Mem

device : "cuda"
num_gpu : 1

learning_rate: 1.e-3
lr_step_size : 1
lr_gamma : 0.85
gradient_clip : 0.5
weight_decay: 1.e-6
adam_epsilon : 1.e-8
num_train_epochs : 80

train_version : 0
train_name : 'baseline'
save_top_k : 5
resume : True
seed : 2024

# MACs in 16000: 62.15731377154589 G/s, Parameters: 32.0456657409668 M
# MACs in 48000: 78.43080977350473 G/s, Parameters: 36.01795196533203 M
# ~ 38M
model_type: "discriminative"
init_from : 'none'
se_model: bsrnn
model_configs:
  num_channel: 196
  num_layer: 6 

